#pragma once

#include "graphics/Circle.h"
#include "graphics/Ellipse.h"
#include "graphics/ColorShape.h"
#include "graphics/Group.h"
#include "graphics/LinearGradient.h"
#include "graphics/Path.h"
#include "graphics/Polygon.h"
#include "graphics/Polyline.h"
#include "graphics/RadialGradient.h"
#include "graphics/Rectangle.h"
#include "graphics/Text.h"
#include "graphics/ViewBox.h"
#include "graphics/Line.h"